# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _ClipboardBackend
else:
    import _ClipboardBackend

import builtins as __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _ClipboardBackend.delete_SwigPyIterator

    def value(self):
        return _ClipboardBackend.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _ClipboardBackend.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _ClipboardBackend.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _ClipboardBackend.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _ClipboardBackend.SwigPyIterator_equal(self, x)

    def copy(self):
        return _ClipboardBackend.SwigPyIterator_copy(self)

    def next(self):
        return _ClipboardBackend.SwigPyIterator_next(self)

    def __next__(self):
        return _ClipboardBackend.SwigPyIterator___next__(self)

    def previous(self):
        return _ClipboardBackend.SwigPyIterator_previous(self)

    def advance(self, n):
        return _ClipboardBackend.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _ClipboardBackend.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _ClipboardBackend.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _ClipboardBackend.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _ClipboardBackend.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _ClipboardBackend.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _ClipboardBackend.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _ClipboardBackend:
_ClipboardBackend.SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _ClipboardBackend.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _ClipboardBackend.IntVector___nonzero__(self)

    def __bool__(self):
        return _ClipboardBackend.IntVector___bool__(self)

    def __len__(self):
        return _ClipboardBackend.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _ClipboardBackend.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _ClipboardBackend.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _ClipboardBackend.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _ClipboardBackend.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _ClipboardBackend.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _ClipboardBackend.IntVector___setitem__(self, *args)

    def pop(self):
        return _ClipboardBackend.IntVector_pop(self)

    def append(self, x):
        return _ClipboardBackend.IntVector_append(self, x)

    def empty(self):
        return _ClipboardBackend.IntVector_empty(self)

    def size(self):
        return _ClipboardBackend.IntVector_size(self)

    def swap(self, v):
        return _ClipboardBackend.IntVector_swap(self, v)

    def begin(self):
        return _ClipboardBackend.IntVector_begin(self)

    def end(self):
        return _ClipboardBackend.IntVector_end(self)

    def rbegin(self):
        return _ClipboardBackend.IntVector_rbegin(self)

    def rend(self):
        return _ClipboardBackend.IntVector_rend(self)

    def clear(self):
        return _ClipboardBackend.IntVector_clear(self)

    def get_allocator(self):
        return _ClipboardBackend.IntVector_get_allocator(self)

    def pop_back(self):
        return _ClipboardBackend.IntVector_pop_back(self)

    def erase(self, *args):
        return _ClipboardBackend.IntVector_erase(self, *args)

    def __init__(self, *args):
        _ClipboardBackend.IntVector_swiginit(self, _ClipboardBackend.new_IntVector(*args))

    def push_back(self, x):
        return _ClipboardBackend.IntVector_push_back(self, x)

    def front(self):
        return _ClipboardBackend.IntVector_front(self)

    def back(self):
        return _ClipboardBackend.IntVector_back(self)

    def assign(self, n, x):
        return _ClipboardBackend.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _ClipboardBackend.IntVector_resize(self, *args)

    def insert(self, *args):
        return _ClipboardBackend.IntVector_insert(self, *args)

    def reserve(self, n):
        return _ClipboardBackend.IntVector_reserve(self, n)

    def capacity(self):
        return _ClipboardBackend.IntVector_capacity(self)
    __swig_destroy__ = _ClipboardBackend.delete_IntVector

# Register IntVector in _ClipboardBackend:
_ClipboardBackend.IntVector_swigregister(IntVector)


def init():
    return _ClipboardBackend.init()

def shutdown():
    return _ClipboardBackend.shutdown()

def prepareForPasting(renderFunc, availableClipboardFormats):
    return _ClipboardBackend.prepareForPasting(renderFunc, availableClipboardFormats)

def waitForPaste(msTimeout):
    return _ClipboardBackend.waitForPaste(msTimeout)

def finalizePasting():
    return _ClipboardBackend.finalizePasting()

def prepareForClipboardToChange():
    return _ClipboardBackend.prepareForClipboardToChange()

def hasClipboardChanged():
    return _ClipboardBackend.hasClipboardChanged()

def waitForClipboardToChange(msTimeout):
    return _ClipboardBackend.waitForClipboardToChange(msTimeout)


